name: "Delete self-destructing tweets every six hours."

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch: {}

jobs:
  self-destruct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - run: |
          dotnet tool restore
          dotnet script scripts/self-destruct-tweets.csx
        shell: pwsh
        env:
          TWITTER_CONSUMER_TOKEN: ${{ secrets.TWITTER_CONSUMER_TOKEN }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_USER_TOKEN: ${{ secrets.TWITTER_USER_TOKEN }}
          TWITTER_USER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
